name: Linter

on: push

jobs:
  build:
    runs-on: ubuntu-latest
     
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        
    steps:
    - uses: actions/checkout@v2
      
    - name: PHP Setup
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, dom, pgsql
        tools: prestessimo

    - name: Install
      run: make setup

    - name: Lint 
      run: make lint
